### ISSUE TITLE
Get on it!!!

### ISSUE THREAD

**Issue by justmesam** [builtIT/La_music#1]
Yoh I think its time we started contributing to this app since everyone is well conversant with coding and best practices. @Gidraff  @betsybeth  @belio39 
react with 👍  to agree or 👎  to disagree else give me your thought.

**Comment by belio39** [comment]
👍

[image: MailTag]  Sent with MailTag <https://www.mailtag.io>

**Comment by Gidraff** [comment]
👍

**Comment by betsybeth** [comment]
hey @justmesam I got the message late.I am in
